####################################################################################333
def CreateMaterialDict(): # List of classes for the OpenSurfaces Data set
        MaterialDict={}
        i=1
        MaterialDict[i]="Brick"
        i+=1
        MaterialDict[i]="Cardboard"
        i+=1
        MaterialDict[i]="Carpet / rug"
        i+=1
        MaterialDict[i]="Ceramic"
        i+=1
        MaterialDict[i]="Chalkboard / blackboard"
        i+=1
        MaterialDict[i]="Concrete"
        i+=1
        MaterialDict[i]="Cork / corkboard"
        i+=1
        MaterialDict[i]="Dirt"
        i+=1
        MaterialDict[i]="Fabric / cloth"
        i+=1
        MaterialDict[i]="Fire"
        i+=1
        MaterialDict[i]="Foliage"
        i+=1
        MaterialDict[i]="Food"
        i+=1
        MaterialDict[i]="Fur"
        i+=1
        MaterialDict[i]="Glass"
        i+=1
        MaterialDict[i]="Granite"
        i+=1
        MaterialDict[i]="Granite / marble"
        i+=1
        MaterialDict[i]="Hair"
        i+=1
        MaterialDict[i]="Laminate"
        i+=1
        MaterialDict[i]="Leather"
        i+=1
        MaterialDict[i]="Linoleum"
        i+=1
        MaterialDict[i]="Marble"
        i+=1
        MaterialDict[i]="Metal"
        i+=1
        MaterialDict[i]="Mirror"
        i+=1
        MaterialDict[i]="Painted"
        i+=1
        MaterialDict[i]="Paper towel / tissue"
        i+=1
        MaterialDict[i]="Paper / tissue"
        i+=1
        MaterialDict[i]="Plaster"
        i+=1
        MaterialDict[i]="Plastic - clear"
        i+=1
        MaterialDict[i]="Plastic - opaque"
        i+=1
        MaterialDict[i]="Rubber / latex"
        i+=1
        MaterialDict[i]="Skin"
        i+=1
        MaterialDict[i]="Sky"
        i+=1
        MaterialDict[i]="Sponge"
        i+=1
        MaterialDict[i]="Stone"
        i+=1
        MaterialDict[i]="Styrofoam"
        i+=1
        MaterialDict[i]="Tile"
        i+=1
        MaterialDict[i]="Wallboard - painted"
        i+=1
        MaterialDict[i]="Wallboard - unpainted"
        i+=1
        MaterialDict[i]="Wallpaper"
        i+=1
        MaterialDict[i]="Water"
        i+=1
        MaterialDict[i]="Wax"
        i+=1
        MaterialDict[i]="Wicker"
        i+=1
        MaterialDict[i]="Wood"
        i+=1
        MaterialDict[i]="Wood - natural color"
        i+=1
        MaterialDict[i]="Wood - painted"
        return MaterialDict

